######################################################################
# Automatically generated by qmake (3.0) Tue Aug 18 17:52:03 2015
######################################################################

TEMPLATE = app
TARGET = rubikGL
INCLUDEPATH += .
QT += opengl
LIBS += -lglut -lGLU
# Input
HEADERS += cubie.h glwidget.h rubikCube.h window.h
SOURCES += cubie.cpp glwidget.cpp main.cpp rubikCube.cpp window.cpp
