######################################################################
# Automatically generated by qmake (3.0) dom sep 1 05:53:34 2013
######################################################################

TEMPLATE = app
TARGET = RubikGL
INCLUDEPATH += .
QT += opengl
LIBS += -lGLU

# Input
HEADERS += cubie.h glwidget.h rubikCube.h window.h
SOURCES += cubie.cpp glwidget.cpp main.cpp rubikCube.cpp window.cpp
