# #####################################################################
# Automatically generated by qmake (2.01a) vie dic 25 03:21:16 2009
# #####################################################################
TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += cubie.h \
	rubikCube.h \
	glwidget.h \
	window.h
SOURCES += cubie.cpp \
	rubikCube.cpp \
	glwidget.cpp \
	main.cpp \
	window.cpp
RESOURCES +=
